backend:
  name: git-gateway
  branch: main

media_folder: "website/images/uploads"
public_folder: "/images/uploads"

locale: "fa"

collections:
  - name: "articles"
    label: "مقالات"
    folder: "website/articles"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ", name: "date", widget: "datetime" }
      - { label: "نویسنده", name: "author", widget: "string", default: "مدهوش" }
      - label: "دسته‌بندی"
        name: "category"
        widget: "select"
        required: false
        options: ["پشت صحنه", "اخبار", "داستان آهنگ", "گفتگو"]
      - { label: "تصویر", name: "thumbnail", widget: "image", required: false, hint: "ابعاد پیشنهادی: ۱۲۰۰×۶۳۰ پیکسل" }
      - { label: "خلاصه", name: "description", widget: "text", hint: "خلاصه‌ای ۲-۳ خطی که در لیست مقالات نمایش داده می‌شود" }
      - { label: "متن", name: "body", widget: "markdown" }
